/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSettingsTab: typeof import('./src/components/settings/tabs/AppSettingsTab.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ContainerComponent: typeof import('./src/components/ui/ContainerComponent.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    PulseLogo: typeof import('./src/components/icons/PulseLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SidebarItem: typeof import('./src/components/sidebar/SidebarItem.vue')['default']
    SidebarNav: typeof import('./src/components/sidebar/SidebarNav.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    UserAvatar: typeof import('./src/components/ui/UserAvatar.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserSettingsDrawer: typeof import('./src/components/settings/UserSettingsDrawer.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
